const languages = [
  {
    name: "english",
    errors: {
      error: "Error",
      emailEmpty: "Please fill in the email field.",
      emailInvalid: "Invalid email. Please try again.",
      passEmpty: "Please fill in the password field.",
      passInvalid: "Password must have at least 1 number, 1 symbol, and 8 letters.",
      nameEmpty: "Please fill in the name field.",
      nameInvalid: "Name must not contain numbers or symbols.",
      heightEmpty: "Please fill in the height field.",
      heightInvalid: "Invalid height. Please try again.",
      weightEmpty: "Please fill in the weight field.",
      weightInvalid: "Invalid weight. Please try again.",
      userNotFound: "No user corresponds to those credentials.",
      networkError: "Network error. Please try again.",
      unhandledError: "An unhandled error has occured: \n\n",
      googlePlayServicesMissing: "Fatal Error: cannot sign in. Please update Google Play Services",
      imageNetworkError: "Network error while uploading image.",
      imageUnhandledError: "An unhandled error while uploading image has occured: \n\n",
      thirdPartyPassResetError: "Error: this feature is not available for users who signed up with Google or Facebook.",
      thirdPartyLoginError: "Error: you already registered with a different credential provider.",
      ageEmpty: "Please fill in the birth date field.",
      emailInUse: "That email is already in use. Please try again.",
      timeError: "Invalid time. Please try again.",
      mapError: "Unknown error with location: \n\n",
      mapPermError: "You must allow location permissions to use maps.",
      passIncorrect: "Incorrect password.",
      tooManyAttempts: "Too many password attempts. Try again later.",
      titleEmptyError: "Please fill in the title field.",
      descEmptyError: "Please fill in the description field."
    },
    labels: {
      error: "Error",
      registerText: "Don't have an account?",
      resetPassText: "Forgot your password?",
      storagePermissionTitle: "Sportsmart requires your storage permission",
      storagePermissionText: "Sportsmart needs access to your storage in order to set your profile image.",
      locationPermissionTitle: "Sportsmart requires your location permission",
      locationPermissionText: "Sportsmart needs access to your location in order to track your walking distance.",
      resetPassScreenText: "Please enter your registered Email to reset your password.",
      users: "Users",
      activity: "Activity",
      calories: "Calories",
      duration: "Duration",
      distance: "Distance",
      speed: "Speed",
      statistics: "Statistics",
      settings: "Settings",
      support: "Support",
      instructions: "Instructions",
      running: "Running",
      notifiers: "Notifications",
      profile: "Profile",
      metric: "Metric",
      imperial: "Imperial",
      email: "Email",
      password: "Password",
      name: "Name",
      bio: "Description (optional)",
      height: "Height",
      weight: "Weight",
      login: "Login",
      logOut: "Log Out",
      register: "Register",
      resetPass: "Reset Password",
      signOut: "Sign Out",
      born: "Birth date",
      kjoules: "Kilojoules",
      male: "Male",
      female: "Female",
      genderText: "Gender",
      pause: "Pause",
      createNotifier: "Edit Notification",
      time: "Set the time",
      description: "Description",
      finish: "Finish",
      delete: "Delete",
      alarmSet: "Alarm set for {0} hour/s and {1} minute/s",
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
      activityPerDay: "Daily Activity",
      gender: { male: "Male", female: "Female" },
      noNotifiers: "You currently have no notification set.",
      changeLanguage: "Change language",
      language: "Language",
      disableAllNotifs: "Delete all notifications",
      notifsDeleted: "Deleted {0} notifications",
      deleteAccount: "Delete Sportsmart Account",
      confirmDeletion: "Additional confirmation needed",
      confirmDeletionText: "In order to make sure you want to delete your account, you need to input your password below.",
      confirmDeletionText2: "In order to make sure you want to delete your account, you need to confirm deletion.",
      createdBy: "Created by Leo Petrovic",
      noData1: "No data. Go to the ",
      noData2: " 'Running' screen to get statistics about your activity.",
      noData: "No data.",
      searchUsers: "Search Users...",
      loading: "Loading",
      editProfile: "Edit profile",
      supportText: "If you had any diffculty using our app, we would appreciate if you would describe the problem you encountered in detail.",
      supportTitle: "Report subject",
      supportDesc: "Detailed problem description (device operating system, in which part of the app did the problem occur and when, and how to reproduce the problem)",
      title: "Title",
      supportSubmit: "Thank you for submitting a report!",
      supportSubmitTimeout: "You must wait 30 seconds between report submissions",
      additionalInfoText: "We require additional info from you in order to provide you with statistics info.",
      alarmStart: "Alarm has expired. Start running!",
      howToStart: "How To Start",
      howToStartText1: "Go to the ",
      howToStartText2: " Running screen and press the START button to start your activity.",
      findStatisticsText: "You can find info about your activity on the Profile screen, or on the Statistics screen on the side drawer.",
      findStatisticsText2: "You can search other Users and view their statistics and other info, on the side drawer as well.",
      medals: "Medals",
      medalsUseText: "You can get various medals as a reward for your activity, and they are: ",
      medalsTexts: ["Surpassing your Daily Activity bar", "Being active for more than an hour", "Travelling for more than 10 kilometers/6.2 miles"]
    }
  },
  {
    name: "lokalni (BiH)",
    errors: {
      error: "Greška",
      emailEmpty: "Molimo vas da ispunite polje za email.",
      emailInvalid: "Nevažeći email. Molimo vas pokušajte ponovo.",
      passEmpty: "Molimo vas da ispunite polje za lozinku.",
      passInvalid: "Password mora imati jedan broj, jedan simbol, i najmanje 8 slova.",
      nameEmpty: "Molimo vas da ispunite ime.",
      nameInvalid: "Ime ne smije sadržavati simbole ili brojeve.",
      heightEmpty: "Molimo vas da ispunite polje za visinu.",
      heightInvalid: "Nevažeća visina. Molimo vas pokušajte ponovo.",
      weightEmpty: "Molimo vas da ispunite polje za težinu.",
      weightInvalid: "Nevažeća težina. Molimo vas pokušajte ponovo.",
      userNotFound: "Taj korisnik nije pronađen.",
      networkError: "Pogreška sa mrežom, molimo vas pokušajte ponovo.",
      unhandledError: "Nepoznata pogreška: \n\n",
      googlePlayServicesMissing: "Pogreška u prijavi. Molimo vas ažurirajte Google Play Services",
      imageNetworkError: "Pogreška sa mrežom tijekom učitavanje slike.",
      imageUnhandledError: "Nepoznata pogreška tijekom učitavanje slike: \n\n",
      thirdPartyPassResetError: "Pogreška: ova mogućnost nije dostupna korisnicima koji su se prijavili putem Google-a ili Facebook-a.",
      thirdPartyLoginError: "Pogreška: već ste se registrirali putem drugog opskrbljivača.",
      ageEmpty: "Molimo vas da ispunite polje za datum rođenja",
      emailInUse: "Taj email je već u uporabi. Molimo vas pokušajte ponovo.",
      timeError: "Nevažeće vrijeme. Molimo pokušajte ponovo.",
      mapError: "Nepoznata greška sa lokacijom: \n\n",
      mapPermError: "Morate dozvoliti pristup lokaciji da biste koristili mapu.",
      passIncorrect: "Netočna lozinka.",
      tooManyAttempts: "Previše pokušaja za upis lozinke. Pokušajte ponovo kasnije.",
      titleEmptyError: "Molimo vas ispunite polje za naslov.",
      descEmptyError: "Molimo vas ispunite polje za opis."
    },
    labels: {
      error: "Greška",
      registerText: "Nemate račun?",
      resetPassText: "Zaboravili ste lozinku?",
      storagePermissionTitle: "Sportsmart zahtijeva pristup unutarnjoj pohrani vašeg uređaja.",
      storagePermissionText: "Sportsmartu treba pristup unutarnjoj pohrani vašeg uređaja da biste postavili profilnu sliku.",
      locationPermissionTitle: "Sportsmart zahtijeva pristup vašoj lokaciji.",
      locationPermissionText: "Sportsmartu treba pristup vašoj lokaciji da biste mogli pratiti korake i udaljenost.",
      resetPassScreenText: "Molimo vas da unesete vaš prijavljeni Email da biste promjenili lozinku.",
      users: "Korisnici",
      activity: "Aktivnost",
      calories: "Kalorije",
      duration: "Trajanje",
      distance: "Udaljenost",
      speed: "Brzina",
      statistics: "Statistike",
      settings: "Postavke",
      support: "Podrška",
      instructions: "Upute Korištenja",
      running: "Trening",
      notifiers: "Planirani Treninzi",
      profile: "Profil",
      email: "Email",
      password: "Lozinka",
      name: "Ime",
      bio: "Opis (neobavezno)",
      height: "Visina",
      weight: "Težina",
      login: "Prijava",
      logOut: "Odjavi se",
      register: "Registriraj se",
      resetPass: "Promjeni lozinku",
      signOut: "Odjavi se",
      born: "Datum rođenja",
      kjoules: "Kilodžuli",
      male: "Muško",
      female: "Žensko",
      pause: "Pauza",
      createNotifier: "Namjesti planirani trening",
      time: "Namjesti vrijeme",
      description: "Opis",
      finish: "Završi",
      delete: "Izbriši",
      alarmSet: "Vrijeme postavljeno za {0} sat/i i {1} minut/a",
      days: ["Nedjelja", "Ponedjeljak", "Utorak", "Srijeda", "Četvrtak", "Petak", "Subota"],
      activityPerDay: "Dnevna aktivnost",
      gender: { male: "Muško", female: "Žensko" },
      genderText: "Spol",
      noNotifiers: "Trenutno nemate nijedan planirani trening postavljen.",
      changeLanguage: "Promijenite jezik",
      language: "Jezik",
      disableAllNotifs: "Izbriši sve obavijesti",
      notifsDeleted: "{0} obavijesti izbrisano",
      deleteAccount: "Izbriši Sportsmart Račun",
      confirmDeletion: "Dodatna potvrda je potrebna",
      confirmDeletionText: "Da bi bili sigurni da želite izbrisati svoj račun, morate unijeti lozinku.",
      confirmDeletionText2: "Da bi bili sigurni da želite izbrisati svoj račun, morate potvrditi.",
      createdBy: "Napravio - Leo Petrović",
      noData1: "Nema podataka. Idite na ",
      noData: "Nema podataka.",
      noData2: " 'Trening' da biste skupili statistike o svojoj aktivnosti.",
      searchUsers: "Pretraži korisnike...",
      loading: "Učitavanje",
      editProfile: "Uredi profil",
      supportText: "Ako imate ikakvih poteškoća tijekom korištenja aplikacije, molimo vas da nam pošaljete detaljnu prijavu problema u formularu ispod.",
      supportTitle: "Kratki naslov prijave",
      supportDesc: "Detaljni opis problema (operativni sustav uređaja, gdje se u aplikaciji dogodila pogreška i kada, i kako se problem može reproducirati)",
      title: "Naslov",
      supportSubmit: "Hvala vam na podršci!",
      supportSubmitTimeout: "Morate pričekati 30 sekundi između slanja prijava",
      additionalInfoText: "Mi zahtijevamo dodatne informacije od vas kako biste dobili uvid u statistike i aktivnost.",
      alarmStart: "Alarm je završio. Počni se kretati!",
      howToStart: "Kako početi",
      howToStartText1: "Idite na ",
      howToStartText2: " Trening i pritisnite gumb START da biste počeli trening.",
      findStatisticsText: "Možete naći informacije o svojoj aktivnosti na svom Profilu ili na Statistikama sa menija sa strane.",
      findStatisticsText2: "Također možete vidjeti statistike i ostale informacije o drugim Korisnicima sa menija sa strane.",
      medals: "Medalje",
      medalsUseText: "Možete dobiti razne medalje za svoju aktivnost, a to su: ",
      medalsTexts: ["Premašivanje svog cilja Dnevne Aktivnosti", "Aktivnost duža od jednog sata", "Premašivanje više od 10 kilometara"]
    }
  }
];

const defaultLang = languages[1];  // 0 - English,   1 - Hrvatski
const currentLang = defaultLang;

export default {
  currentLang: currentLang,
  languages: languages
}