const languages = [
  {
    name: "english",
    errors: {
      error: "Error",
      emailEmpty: "Please fill in the email field.",
      emailInvalid: "Invalid email. Please try again.",
      passEmpty: "Please fill in the password field.",
      passInvalid: "Password must have at least 1 number, 1 symbol, and 8 letters.",
      nameEmpty: "Please fill in the name field.",
      nameInvalid: "Name must not contain numbers or symbols.",
      heightEmpty: "Please fill in the height field.",
      heightInvalid: "Invalid height. Please try again.",
      weightEmpty: "Please fill in the weight field.",
      weightInvalid: "Invalid weight. Please try again.",
      userNotFound: "No user corresponds to those credentials.",
      networkError: "Network error. Please try again.",
      unhandledError: "An unhandled error has occured: \n\n",
      googlePlayServicesMissing: "Fatal Error: cannot sign in. Please update Google Play Services",
      imageNetworkError: "Network error while uploading image.",
      imageUnhandledError: "An unhandled error while uploading image has occured: \n\n",
      thirdPartyPassResetError: "Error: this feature is not available for users who signed up with Google or Facebook.",
      thirdPartyLoginError: "Error: you already registered with a different credential provider.",
      ageEmpty: "Please fill in the birth date field.",
      emailInUse: "That email is already in use. Please try again.",
      timeError: "Invalid time. Please try again.",
      mapError: "Unknown error with location: \n\n",
      mapPermError: "You must allow location permissions to use maps.",
      passIncorrect: "Incorrect password.",
      tooManyAttempts: "Too many password attempts. Try again later."
    },
    labels: {
      error: "Error",
      registerText: "Don't have an account?",
      resetPassText: "Forgot your password?",
      storagePermissionTitle: "Sportsmart requires your storage permission",
      storagePermissionText: "Sportsmart needs access to your storage in order to set your profile image.",
      locationPermissionTitle: "Sportsmart requires your location permission",
      locationPermissionText: "Sportsmart needs access to your location in order to track your walking distance.",
      resetPassScreenText: "Please enter your registered Email to reset your password.",
      together: "Together",
      activity: "Activity",
      calories: "Calories",
      duration: "Duration",
      distance: "Distance",
      speed: "Speed",
      statistics: "Statistics",
      settings: "Settings",
      support: "Support",
      running: "Running",
      notifiers: "Notifiers",
      profile: "Profile",
      metric: "Metric",
      imperial: "Imperial",
      email: "Email",
      password: "Password",
      name: "Name",
      bio: "Description (optional)",
      height: "Height",
      weight: "Weight",
      login: "Login",
      logOut: "Log Out",
      register: "Register",
      resetPass: "Reset Password",
      signOut: "Sign Out",
      born: "Birth date",
      kjoules: "Kilojoules",
      male: "Male",
      female: "Female",
      genderText: "Gender",
      pause: "Pause",
      createNotifier: "Edit Notifier",
      time: "Set the time",
      description: "Description",
      finish: "Finish",
      delete: "Delete",
      alarmSet: "Alarm set for {0} hour/s and {1} minute/s",
      months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
      activityPerMonth: "Monthly Activity",
      gender: { male: "Male", female: "Female" },
      noNotifiers: "You currently have no notifiers set.",
      changeLanguage: "Change language",
      language: "Language",
      disableAllNotifs: "Delete all notifiers",
      notifsDeleted: "Deleted {0} notifiers",
      deleteAccount: "Delete Account",
      confirmDeletion: "Additional confirmation needed",
      confirmDeletionText: "In order to make sure you want to delete your account, you need to input your password below.",
      createdBy: "Created by Leo Petrovic",
      noData1: "No data. Go to the ",
      noData2: " 'Running' screen to get statistics about your activity."
    }
  },
  {
    name: "hrvatski",
    errors: {
      error: "Greška",
      emailEmpty: "Molimo vas da ispunite polje za email.",
      emailInvalid: "Nevažeći email. Molimo vas pokušajte ponovo.",
      passEmpty: "Molimo vas da ispunite polje za lozinku.",
      passInvalid: "Password mora imati jedan broj, jedan simbol, i najmanje 8 slova.",
      nameEmpty: "Molimo vas da ispunite ime.",
      nameInvalid: "Ime ne smije sadržavati simbole ili brojeve.",
      heightEmpty: "Molimo vas da ispunite polje za visinu.",
      heightInvalid: "Nevažeća visina. Molimo vas pokušajte ponovo.",
      weightEmpty: "Molimo vas da ispunite polje za težinu.",
      weightInvalid: "Nevažeća težina. Molimo vas pokušajte ponovo.",
      userNotFound: "Taj korisnik nije pronađen.",
      networkError: "Pogreška sa mrežom, molimo vas pokušajte ponovo.",
      unhandledError: "Nepoznata pogreška: \n\n",
      googlePlayServicesMissing: "Pogreška u prijavi. Molimo vas ažurirajte Google Play Services",
      imageNetworkError: "Pogreška sa mrežom tijekom učitavanje slike.",
      imageUnhandledError: "Nepoznata pogreška tijekom učitavanje slike: \n\n",
      thirdPartyPassResetError: "Pogreška: ova mogućnost nije dostupna korisnicima koji su se prijavili putem Google-a ili Facebook-a.",
      thirdPartyLoginError: "Pogreška: već ste se registrirali putem drugog opskrbljivača.",
      ageEmpty: "Molimo vas da ispunite polje za datum rođenja",
      emailInUse: "Taj email je već u uporabi. Molimo vas pokušajte ponovo.",
      timeError: "Nevažeće vrijeme. Molimo pokušajte ponovo.",
      mapError: "Nepoznata greška sa lokacijom: \n\n",
      mapPermError: "Morate dozvoliti pristup lokaciji da biste koristili mapu.",
      passIncorrect: "Netočna lozinka.",
      tooManyAttempts: "Previše pokušaja za upis lozinke. Pokušajte ponovo kasnije."
    },
    labels: {
      error: "Greška",
      registerText: "Nemate račun?",
      resetPassText: "Zaboravili ste lozinku?",
      storagePermissionTitle: "Sportsmart zahtijeva pristup unutarnjoj pohrani vašeg uređaja.",
      storagePermissionText: "Sportsmartu treba pristup unutarnjoj pohrani vašeg uređaja da biste postavili profilnu sliku.",
      locationPermissionTitle: "Sportsmart zahtijeva pristup vašoj lokaciji.",
      locationPermissionText: "Sportsmartu treba pristup vašoj lokaciji da biste mogli pratiti korake i udaljenost.",
      resetPassScreenText: "Molimo vas da unesete vaš prijavljeni Email da biste promjenili lozinku.",
      together: "Zajedno",
      activity: "Aktivnost",
      calories: "Kalorije",
      duration: "Trajanje",
      distance: "Udaljenost",
      speed: "Brzina",
      statistics: "Statistike",
      settings: "Postavke",
      support: "Podrška",
      running: "Trening",
      notifiers: "Obavijesti",
      profile: "Profil",
      email: "Email",
      password: "Lozinka",
      name: "Ime",
      bio: "Opis (neobavezno)",
      height: "Visina",
      weight: "Težina",
      login: "Prijava",
      logOut: "Odjavi se",
      register: "Registriraj se",
      resetPass: "Promjeni lozinku",
      signOut: "Odjavi se",
      born: "Datum rođenja",
      kjoules: "Kilodžuli",
      male: "Muško",
      female: "Žensko",
      pause: "Pauza",
      createNotifier: "Namjesti obavijest",
      time: "Namjesti vrijeme",
      description: "Opis",
      finish: "Završi",
      delete: "Izbriši",
      alarmSet: "Vrijeme postavljeno za {0} sat/i and {1} minut/a",
      months: ["Siječanj", "Veljača", "Ožujak", "Travanj", "Svibanj", "Lipanj", "Srpanj", "Kolovoz", "Rujan", "Listopad", "Studeni", "Prosinac"],
      activityPerMonth: "Mjesečna aktivnost",
      gender: { male: "Muško", female: "Žensko" },
      genderText: "Spol",
      noNotifiers: "Trenutno nemate nijednu obavijest postavljenu.",
      changeLanguage: "Promijenite jezik",
      language: "Jezik",
      disableAllNotifs: "Izbriši sve obavijesti",
      notifsDeleted: "{0} obavijesti izbrisano",
      deleteAccount: "Izbriši Račun",
      confirmDeletion: "Dodatna potvrda je potrebna",
      confirmDeletionText: "Da bi bili sigurni da želite izbrisati svoj račun, morate unijeti lozinku.",
      createdBy: "Napravio - Leo Petrović",
      noData1: "Nema podataka. Idite na ",
      noData2: " 'Trening' da bi skupili statistike o svojoj aktivnosti."
    }
  }
];

const defaultLang = languages[1];  // 0 - English,   1 - Hrvatski
const currentLang = defaultLang;

export default {
  currentLang: currentLang,
  languages: languages
}